import { ByteProcessor, IDATA_PROPS, IMASS_TRANSFER_PROPS, ISET_SCRIPT_PROPS, ISPONSORSHIP_PROPS } from '..';
import { IBURN_PROPS, ICANCEL_LEASING_PROPS, ICANCEL_ORDER_PROPS, ICREATE_ALIAS_PROPS, IDEFAULT_PROPS, IISSUE_PROPS, ILEASE_PROPS, IORDER_PROPS, IREISSUE_PROPS, ISignatureGeneratorConstructor, ITRANSFER_PROPS, TTX_NUMBER_MAP, TTX_TYPE_MAP } from './interface';
export declare function generate<T>(fields: Array<ByteProcessor | number>): ISignatureGeneratorConstructor<T>;
export declare const TX_NUMBER_MAP: TTX_NUMBER_MAP;
export declare const TX_TYPE_MAP: TTX_TYPE_MAP;
export declare const CREATE_ORDER_SIGNATURE: ISignatureGeneratorConstructor<IORDER_PROPS>;
export declare const AUTH_ORDER_SIGNATURE: ISignatureGeneratorConstructor<IDEFAULT_PROPS>;
export declare const CANCEL_ORDER_SIGNATURE: ISignatureGeneratorConstructor<ICANCEL_ORDER_PROPS>;
export declare const ISSUE: ISignatureGeneratorConstructor<IISSUE_PROPS>;
export declare const TRANSFER: ISignatureGeneratorConstructor<ITRANSFER_PROPS>;
export declare const REISSUE: ISignatureGeneratorConstructor<IREISSUE_PROPS>;
export declare const BURN: ISignatureGeneratorConstructor<IBURN_PROPS>;
export declare const LEASE: ISignatureGeneratorConstructor<ILEASE_PROPS>;
export declare const CANCEL_LEASING: ISignatureGeneratorConstructor<ICANCEL_LEASING_PROPS>;
export declare const CREATE_ALIAS: ISignatureGeneratorConstructor<ICREATE_ALIAS_PROPS>;
export declare const MASS_TRANSFER: ISignatureGeneratorConstructor<IMASS_TRANSFER_PROPS>;
export declare const DATA: ISignatureGeneratorConstructor<IDATA_PROPS>;
export declare const SET_SCRIPT: ISignatureGeneratorConstructor<ISET_SCRIPT_PROPS>;
export declare const SPONSORSHIP: ISignatureGeneratorConstructor<ISPONSORSHIP_PROPS>;
